### ISSUE TITLE
Disable Touch

### ISSUE THREAD

**Issue by 1Map** [Paroca72/sc-gauges#8]
How do I disable any touch on the gauges?

**Comment by Paroca72** [comment]
Hello,

Usually `setRecognizePathTouch` to `false` should be enough for this..
But it start `false` by default so:
Maybe you have a particular case? 
Can you give me some more details?

Thanks
Sam

**Comment by 1Map** [comment]
Hi Sam,

Thanks for getting back to me.  Yes, in my case I have gauges on a ScrollView.  The moment I start scrolling down, the touch events clash with the scroll view.  I basically just have gauges to display Temperature, Humidity, etc. and do not want the user to do any touch events on the gauges, apart from scrolling down to see more gauges.

**Comment by Paroca72** [comment]
Hello,

I'm missing something for sure..


<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sc="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#cccccc">

    <ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fillViewport="true">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:background="#f5f5f5" >

            <com.sccomponents.gauges.ScArcGauge
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="30dp"
                android:background="#f5f5f5"
                sc:angleStart="135"
                sc:angleSweep="270"
                sc:strokeSize="6dp"
                sc:progressSize="4dp"
                sc:value="45"
                sc:pointerRadius="10dp"
                sc:textPosition="middle"
                />

            <com.sccomponents.gauges.ScArcGauge
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="30dp"
                android:background="#f5f5f5"
                sc:angleStart="135"
                sc:angleSweep="270"
                sc:strokeSize="6dp"
                sc:progressSize="4dp"
                sc:value="45"
                sc:pointerRadius="10dp"
                sc:textPosition="middle"
                />

            <com.sccomponents.gauges.ScArcGauge
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:padding="30dp"
                android:background="#f5f5f5"
                sc:angleStart="135"
                sc:angleSweep="270"
                sc:strokeSize="6dp"
                sc:progressSize="4dp"
                sc:value="45"
                sc:pointerRadius="10dp"
                sc:textPosition="middle"
                />

        </LinearLayout>

    </ScrollView>

</LinearLayout>


I tried this test and no have scrolling problems..
Maybe you have some code to give me to better understand where is the issue?

PS: I tested on smartphone with Android 6.0.1

Thanks
Sam

**Comment by 1Map** [comment]
My Error Log when I touch the gauge:

```
10-10 23:11:14.836 31740-31740/com.gbm.grainbinmanager E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
10-10 23:11:14.841 31740-31740/com.gbm.grainbinmanager E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
                                                                               at com.sccomponents.gauges.ScDrawer.findFeatures(ScDrawer.java:697)
                                                                               at com.sccomponents.gauges.ScDrawer.getAutoPathTouchThreshold(ScDrawer.java:282)
                                                                               at com.sccomponents.gauges.ScDrawer.onTouchEvent(ScDrawer.java:480)
                                                                               at android.view.View.dispatchTouchEvent(View.java:10717)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:738)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                               at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:559)
                                                                               at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
                                                                               at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
                                                                               at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                               at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
                                                                               at android.view.View.dispatchPointerEvent(View.java:10946)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5110)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4962)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4645)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4702)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                                                                               at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7000)
                                                                               at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6929)
                                                                               at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6890)
                                                                               at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7110)
                                                                               at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                               at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                           	at android.app.ActivityThread.main(ActivityThread.java:6
10-10 23:11:14.851 31740-31740/com.gbm.grainbinmanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.gbm.grainbinmanager, PID: 31740
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
                                                                             at com.sccomponents.gauges.ScDrawer.findFeatures(ScDrawer.java:697)
                                                                             at com.sccomponents.gauges.ScDrawer.getAutoPathTouchThreshold(ScDrawer.java:282)
                                                                             at com.sccomponents.gauges.ScDrawer.onTouchEvent(ScDrawer.java:480)
                                                                             at android.view.View.dispatchTouchEvent(View.java:10717)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:738)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                                                                             at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:559)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                             at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
                                                                             at android.view.View.dispatchPointerEvent(View.java:10946)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5110)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4962)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4645)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4702)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7000)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6929)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6890)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7110)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                             at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                             at android.os.MessageQueue.next(MessageQueue.java:323)
10-10 23:11:14.852 31740-31740/com.gbm.grainbinmanager E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by 1Map** [comment]
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="10dp"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="5dp"
        android:layout_marginLeft="2dp"
        android:layout_marginRight="2dp"
        android:layout_marginTop="2dp"
        android:background="@drawable/border"
        android:padding="5dip"
        android:layout_margin="5dip"
        android:elevation="20dp"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="5dp"
            android:orientation="horizontal"
            tools:layout_editor_absoluteX="40dp"
            tools:layout_editor_absoluteY="361dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/label_device_address"
                android:textSize="18sp"
                android:textStyle="bold" />

            <Space
                android:layout_width="5dp"
                android:layout_height="wrap_content" />

            <TextView
                android:id="@+id/device_address"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:textSize="18sp" />

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="5dp"
            android:orientation="horizontal"
            tools:layout_editor_absoluteX="20dp"
            tools:layout_editor_absoluteY="365dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/label_state"
                android:textSize="18sp"
                android:textStyle="bold" />

            <Space
                android:layout_width="5dp"
                android:layout_height="wrap_content" />

            <TextView
                android:id="@+id/connection_state"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="@string/disconnected"
                android:textSize="18sp" />
        </LinearLayout>

    </LinearLayout>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fadeScrollbars="true"
        android:isScrollContainer="true"
        android:scrollbarStyle="insideOverlay"
        android:scrollbars="vertical"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <LinearLayout
                android:id="@+id/gatt_gauges"
                android:layout_width="match_parent"
                android:layout_height="150dp"
                android:layout_marginTop="10dp"
                android:orientation="horizontal">

                <FrameLayout
                    android:layout_width="0dp"
                    android:layout_height="150dp"
                    android:layout_weight="1"
                    android:background="?android:attr/colorBackground">

                    <com.sccomponents.gauges.ScArcGauge xmlns:sc="http://schemas.android.com/apk/res-auto"
                        android:id="@+id/tmpgauge"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:paddingBottom="20dp"
                        android:paddingLeft="20dp"
                        android:paddingRight="20dp"
                        android:paddingTop="20dp"
                        sc:angleStart="135"
                        sc:angleSweep="270"
                        sc:notches="80"
                        sc:notchesColor="#000000"
                        sc:notchesLength="10dp"
                        sc:notchesPosition="outside"
                        sc:notchesSize="1dp"
                        sc:pathTouchable="true"
                        sc:progressColor="@android:color/black"
                        sc:progressSize="0dp"
                        sc:strokeColors="#05F8DF|#FFF506|#EB0100"
                        sc:strokeSize="10dp"
                        sc:textAlign="center"
                        sc:textSize="7dp" />

                    <TextView
                        android:id="@+id/counterTmpF"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="top|center_horizontal"
                        android:layout_marginTop="60dp"
                        android:text="---"
                        android:textColor="?attr/colorPrimary"
                        android:textSize="16dp" />

                    <TextView
                        android:id="@+id/counterTmpC"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="top|center_horizontal"
                        android:layout_marginTop="85dp"
                        android:text="---"
                        android:textColor="?attr/colorPrimary"
                        android:textSize="16dp" />

                    <TextView
                        android:id="@+id/counterLblTmp"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="top|center_horizontal"
                        android:layout_marginTop="130dp"
                        android:text="Temp"
                        android:textColor="?attr/colorPrimary"
                        android:textSize="16dp" />

                </FrameLayout>

                <FrameLayout
                    android:layout_width="0dp"
                    android:layout_height="150dp"
                    android:layout_weight="1"
                    android:background="?android:attr/colorBackground">

                    <com.sccomponents.gauges.ScArcGauge xmlns:sc="http://schemas.android.com/apk/res-auto"
                        android:id="@+id/humgauge"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:paddingBottom="20dp"
                        android:paddingLeft="20dp"
                        android:paddingRight="20dp"
                        android:paddingTop="20dp"
                        sc:angleStart="135"
                        sc:angleSweep="270"
                        sc:notches="80"
                        sc:notchesColor="#000000"
                        sc:notchesLength="10dp"
                        sc:notchesPosition="outside"
                        sc:notchesSize="1dp"
                        sc:pathTouchable="true"
                        sc:progressColor="@android:color/black"
                        sc:progressSize="0dp"
                        sc:strokeColors="#972600|#05F8DF"
                        sc:strokeSize="10dp"
                        sc:textAlign="center"
                        sc:textSize="8dp" />

                    <TextView
                        android:id="@+id/counterHum"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="top|center_horizontal"
                        android:layout_marginTop="70dp"
                        android:text="---"
                        android:textColor="?attr/colorPrimary"
                        android:textSize="16dp" />

                    <TextView
                        android:id="@+id/counterLblHum"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="top|center_horizontal"
                        android:layout_marginTop="130dp"
                        android:text="Humidity"
                        android:textColor="?attr/colorPrimary"
                        android:textSize="16dp" />

                </FrameLayout>
            </LinearLayout>

            <LinearLayout
                android:id="@+id/gatt_gauges_cap"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                android:minHeight="200dp"
                android:orientation="horizontal">

                <FrameLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:background="?android:attr/colorBackground"
                    android:padding="20dp">

                    <com.sccomponents.gauges.ScLinearGauge xmlns:sc="http://schemas.android.com/apk/res-auto"
                        android:id="@+id/capgauge"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:minHeight="200dp"
                        android:paddingBottom="20dp"
                        android:paddingLeft="20dp"
                        android:paddingRight="50dp"
                        android:paddingTop="20dp"
                        sc:notches="300"
                        sc:notchesColors="#67ce5c|#f2f200|#e23d3d"
                        sc:notchesLength="10dp"
                        sc:notchesPosition="inside"
                        sc:notchesSize="2dp"
                        sc:orientation="vertical"
                        sc:pathTouchable="true"
                        sc:textAlign="left"
                        sc:textTokens="100%"
                        sc:textUnbend="true" />

                </FrameLayout>

                <FrameLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:background="@drawable/border"
                    android:padding="5dip"
                    android:layout_margin="5dip"
                    android:elevation="20dp"></FrameLayout>

            </LinearLayout>

        </LinearLayout>

    </ScrollView>

</LinearLayout>
```

**Comment by 1Map** [comment]
Problem comes when I try to scroll down and touch the pointer on my gauges, it moves the pointer and does not scroll.  I do not want to move the pointers at all by touch, only by code.

**Comment by 1Map** [comment]
Regarding the bug above in ScDrawer.java (line 696)

```
if ((classRef == null || feature.getClass().isAssignableFrom(classRef)) &&
                        tag == null || feature.getTag().equalsIgnoreCase(tag)) {
```

Shouldn't it read:

```
if ((classRef == null || feature.getClass().isAssignableFrom(classRef)) &&
                        (tag == null || feature.getTag().equalsIgnoreCase(tag))) {
```

That is for the bug, what about disabling touch completely on the gauges ?

**Comment by Paroca72** [comment]
Hello,

Thanks for your bug advice.. I will fix soon when I'm back home..

For disable the touch the only way is to set `setRecognizePathTouch` to `false`.

You wrote ".. it moves the pointer .." so this let me understand than your `setRecognizePathTouch` is enabled. Otherwise you should not be able to move the pointer.
As you can see in ScDrawer (line 460)
```
 public boolean onTouchEvent(MotionEvent event) {
        // Check if the input is enabled
        if (!this.mRecognizePathTouch) {
            // Return false mean that on touch event will not capture all the event propagation
            // after the touch event.
            return false;
        }
        ...
```
In other case if you want to have the gauges pointer active and not want to disable the parent mouse capture events you can remove this lines 

`this.getParent().requestDisallowInterceptTouchEvent()`
 
In ScDrawer (line 803) and ScDrawer (line 816)

But this is **not recommended** as create scroll issues in the normal way to use the gauges.

Thanks
Sam
